version: "3"
services:
  spring:
    image: "ekkim329/salesboost-server"
    platform: linux/amd64
    container_name: backend
    ports:
      - "8080:8080"
    build: .
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    hostname: "redis"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    ports:
      - "6379:6379"